# Generated by Django 5.1.7 on 2026-04-09 07:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default='', max_length=200)),
                ('teacher_name', models.CharField(default='', max_length=200)),
                ('room_number', models.CharField(default='', max_length=100)),
                ('activity_mode', models.CharField(default='Lecture', max_length=50)),
                ('num_chairs', models.IntegerField(default=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('date_key', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_rank', models.IntegerField(default=1)),
                ('student_name', models.CharField(default='', max_length=200)),
                ('gesture', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.classsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GestureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_rank', models.IntegerField(default=1)),
                ('student_name', models.CharField(default='', max_length=200)),
                ('gesture', models.CharField(max_length=50)),
                ('activity_mode', models.CharField(default='Lecture', max_length=50)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('warning', 'Warning'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('color', models.CharField(default='#888888', max_length=20)),
                ('label', models.CharField(default='', max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_key', models.DateField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gesture_logs', to='core.classsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_rank', models.IntegerField()),
                ('student_name', models.CharField(default='', max_length=200)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.classsession')),
            ],
            options={
                'ordering': ['chair_rank'],
            },
        ),
    ]
