# Generated by Django 5.1 on 2026-04-01 04:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivity',
            name='seat_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['seat_number'], name='core_studen_seat_nu_727532_idx'),
        ),
    ]
